spring.r2dbc.url=r2dbc:postgresql://localhost:8000/messenger_db
spring.r2dbc.username=postgres
spring.r2dbc.password=houseofwolves20

#spring.mvc.view.prefix=/templates/
#spring.mvc.view.suffix=.html

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.port=8081
