spring.r2dbc.url=r2dbc:postgresql://localhost:8000/messenger_db
spring.r2dbc.username=postgres
spring.r2dbc.password=houseofwolves20
logging.level.web=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:8000/messenger_db
spring.datasource.username=postgres
spring.datasource.password=houseofwolves20
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=very-very-secret-key-should-be-almost-infinity
jwt.expiration=120

attachments.dir=/opt/transparent/

server.port=8081
