spring.r2dbc.url=r2dbc:postgresql://localhost:8000/messenger_db
spring.r2dbc.username=postgres
spring.r2dbc.password=houseofwolves20
jwt.secret=very-very-secret-key-should-be-almost-infinity
jwt.expiration=120

server.port=8081
